// Mock data for demo mode (when Supabase is not configured)
export const MOCK_ITEMS = [
    {
        id: '1',
        title: 'Engineering Mathematics Textbook (3rd Sem)',
        description: 'RD Sharma Engineering Maths. Used for one semester. Minor highlights on a few pages. Great condition overall.',
        price: 350,
        is_barter_only: false,
        is_free: false,
        accept_hybrid: true,
        category: 'Textbooks',
        condition: 'good',
        images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop'],
        hostel_area: 'BH-5',
        is_available: true,
        created_at: '2026-02-20T10:00:00Z',
        seller: { id: 'u1', full_name: 'Arjun Sharma', avatar_url: null, department: 'UIE', hostel: 'BH-5' },
        rating: 4.7,
    },
    {
        id: '2',
        title: 'Casio FX-991EX Scientific Calculator',
        description: 'Perfect working condition. Bought last year. All buttons work fine. Comes with original case.',
        price: 800,
        is_barter_only: false,
        is_free: false,
        accept_hybrid: false,
        category: 'Electronics',
        condition: 'like_new',
        images: ['https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=400&h=400&fit=crop'],
        hostel_area: 'GH-2',
        is_available: true,
        created_at: '2026-02-21T11:00:00Z',
        seller: { id: 'u2', full_name: 'Priya Verma', avatar_url: null, department: 'UIC', hostel: 'GH-2' },
        rating: 4.9,
    },
    {
        id: '3',
        title: 'White Lab Coat (Size M)',
        description: 'Used for 2 semesters. Clean and washed. No stains. Suitable for lab practicals.',
        price: 200,
        is_barter_only: false,
        is_free: false,
        accept_hybrid: true,
        category: 'Lab Equipment',
        condition: 'good',
        images: ['https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&h=400&fit=crop'],
        hostel_area: 'BH-3',
        is_available: true,
        created_at: '2026-02-19T09:30:00Z',
        seller: { id: 'u3', full_name: 'Rohit Mehta', avatar_url: null, department: 'UIE', hostel: 'BH-3' },
        rating: 4.5,
    },
    {
        id: '4',
        title: 'Electric Kettle 1.5L (Prestige)',
        description: 'Working perfectly. Moving out of hostel so selling. Ideal for making Maggi or tea at night.',
        price: 450,
        is_barter_only: false,
        is_free: false,
        accept_hybrid: true,
        category: 'Hostel Essentials',
        condition: 'good',
        images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&h=400&fit=crop'],
        hostel_area: 'BH-7',
        is_available: true,
        created_at: '2026-02-22T14:00:00Z',
        seller: { id: 'u4', full_name: 'Karan Singh', avatar_url: null, department: 'USB', hostel: 'BH-7' },
        rating: 4.8,
    },
    {
        id: '5',
        title: 'Data Structures & Algorithms — Cormen',
        description: 'CLRS 3rd edition. Minor pencil marks. Excellent reference for coding interviews and DSA courses.',
        price: 600,
        is_barter_only: false,
        is_free: false,
        accept_hybrid: false,
        category: 'Textbooks',
        condition: 'good',
        images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop'],
        hostel_area: 'BH-1',
        is_available: true,
        created_at: '2026-02-18T08:00:00Z',
        seller: { id: 'u5', full_name: 'Nisha Gupta', avatar_url: null, department: 'UIC', hostel: 'GH-4' },
        rating: 4.6,
    },
    {
        id: '6',
        title: 'Noise ColorFit Pro 4 Smartwatch',
        description: 'Used for 6 months. In great condition. GPS, heart rate, blood oxygen. Charger included.',
        price: 2200,
        is_barter_only: false,
        is_free: false,
        accept_hybrid: true,
        category: 'Electronics',
        condition: 'like_new',
        images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop'],
        hostel_area: 'BH-9',
        is_available: true,
        created_at: '2026-02-23T16:00:00Z',
        seller: { id: 'u6', full_name: 'Veer Bhatia', avatar_url: null, department: 'AIT', hostel: 'BH-9' },
        rating: 4.9,
    },
    {
        id: '7',
        title: 'Badminton Racket Set (2 rackets + shuttles)',
        description: 'Li-Ning rackets. Used occasionally. Comes with 3 shuttles and a carry bag.',
        price: 0,
        is_barter_only: true,
        is_free: false,
        accept_hybrid: false,
        category: 'Sports & Fitness',
        condition: 'good',
        images: ['https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=400&h=400&fit=crop'],
        hostel_area: 'BH-4',
        is_available: true,
        created_at: '2026-02-21T12:00:00Z',
        seller: { id: 'u7', full_name: 'Ankit Patel', avatar_url: null, department: 'UIE', hostel: 'BH-4' },
        rating: 4.3,
    },
    {
        id: '8',
        title: 'Study Desk Lamp (LED, USB)',
        description: 'Adjustable brightness. USB-powered. Works great. Moving abroad, selling everything.',
        price: 300,
        is_barter_only: false,
        is_free: false,
        accept_hybrid: true,
        category: 'Hostel Essentials',
        condition: 'like_new',
        images: ['https://images.unsplash.com/photo-1513519245088-0e12902e35a7?w=400&h=400&fit=crop'],
        hostel_area: 'GH-3',
        is_available: true,
        created_at: '2026-02-24T10:00:00Z',
        seller: { id: 'u8', full_name: 'Simran Kaur', avatar_url: null, department: 'UILS', hostel: 'GH-3' },
        rating: 4.7,
    },
]

export const MOCK_USER = {
    id: 'demo-user',
    email: 'demo@cuchd.in',
    full_name: 'Demo Student',
    department: 'University Institute of Computing (UIC)',
    hostel: 'BH-5',
    uid: 'CU-2024-001',
    avatar_url: null,
}
